"""Recorded ``ffprobe -v error -print_format json -show_streams -show_format``
output, as dicts, for the offline probe and mezzanine tests.

Real output, trimmed of keys the parser never reads (codec_long_name, the
full disposition block, extradata sizes, the raw display matrix, ...). Every
value the parser does read is verbatim. Three come from the fixture pack and
two from synthetic clips generated with ffmpeg 8.1.1; the exact command sits
above each so the recording can be regenerated.
"""

from typing import Any

__all__ = ["HDR", "MULTITRACK", "PHONE_PORTRAIT", "RTL", "SCREENREC"]

# fixtures/phone_portrait.mov: iPhone SE (2nd gen) camera original. HEVC
# stored as 1920x1080 LANDSCAPE; a rotation=-90 display matrix is the only
# thing that makes it portrait. 30000/1001 fps, one AAC track, three "mebx"
# data streams that must never be mapped.
PHONE_PORTRAIT: dict[str, Any] = {'streams': [{'index': 0,
              'codec_name': 'hevc',
              'codec_type': 'video',
              'codec_tag_string': 'hvc1',
              'width': 1920,
              'height': 1080,
              'pix_fmt': 'yuv420p',
              'color_range': 'tv',
              'color_space': 'bt709',
              'color_transfer': 'bt709',
              'color_primaries': 'bt709',
              'r_frame_rate': '30000/1001',
              'avg_frame_rate': '610800/20381',
              'time_base': '1/600',
              'duration': '33.968333',
              'bit_rate': '13620200',
              'nb_frames': '1018',
              'disposition': {'default': 1},
              'tags': {'language': 'und',
                       'handler_name': 'Core Media Video',
                       'encoder': 'HEVC'},
              'side_data_list': [{'side_data_type': 'Display Matrix', 'rotation': -90}]},
             {'index': 1,
              'codec_name': 'aac',
              'codec_type': 'audio',
              'codec_tag_string': 'mp4a',
              'r_frame_rate': '0/0',
              'avg_frame_rate': '0/0',
              'time_base': '1/44100',
              'duration': '33.966667',
              'bit_rate': '162566',
              'nb_frames': '1465',
              'sample_rate': '44100',
              'channels': 2,
              'channel_layout': 'stereo',
              'disposition': {'default': 1},
              'tags': {'language': 'und', 'handler_name': 'Core Media Audio'}},
             {'index': 2,
              'codec_type': 'data',
              'codec_tag_string': 'mebx',
              'duration': '33.968333',
              'disposition': {'default': 1},
              'tags': {'language': 'und', 'handler_name': 'Core Media Metadata'}},
             {'index': 3,
              'codec_type': 'data',
              'codec_tag_string': 'mebx',
              'duration': '33.968333',
              'disposition': {'default': 1},
              'tags': {'language': 'und', 'handler_name': 'Core Media Metadata'}},
             {'index': 4,
              'codec_type': 'data',
              'codec_tag_string': 'mebx',
              'duration': '33.968333',
              'disposition': {'default': 1},
              'tags': {'language': 'und', 'handler_name': 'Core Media Metadata'}}],
 'format': {'filename': 'fixtures/phone_portrait.mov',
            'nb_streams': 5,
            'format_name': 'mov,mp4,m4a,3gp,3g2,mj2',
            'format_long_name': 'QuickTime / MOV',
            'duration': '33.968333',
            'size': '58865806',
            'bit_rate': '13863690',
            'tags': {'major_brand': 'qt  ',
                     'com.apple.quicktime.model': 'iPhone SE (2nd generation)'}}}

# fixtures/screenrec.mov: QuickTime screen recording. Header claims 120 fps,
# the average is 4168/91 = 45.8 fps (variable frame rate), and there is no
# audio stream at all.
SCREENREC: dict[str, Any] = {'streams': [{'index': 0,
              'codec_name': 'h264',
              'codec_type': 'video',
              'codec_tag_string': 'avc1',
              'width': 3024,
              'height': 1964,
              'pix_fmt': 'yuv420p',
              'color_range': 'tv',
              'color_space': 'bt709',
              'color_transfer': 'bt709',
              'color_primaries': 'bt709',
              'r_frame_rate': '120/1',
              'avg_frame_rate': '4168/91',
              'time_base': '1/600',
              'duration': '33.905000',
              'bit_rate': '10286373',
              'nb_frames': '1563',
              'disposition': {'default': 1},
              'tags': {'language': 'und',
                       'handler_name': 'Core Media Video',
                       'encoder': 'H.264'}}],
 'format': {'filename': 'fixtures/screenrec.mov',
            'nb_streams': 1,
            'format_name': 'mov,mp4,m4a,3gp,3g2,mj2',
            'format_long_name': 'QuickTime / MOV',
            'duration': '33.905000',
            'size': '43902643',
            'bit_rate': '10358977',
            'tags': {'major_brand': 'qt  ',
                     'com.apple.quicktime.author': 'ReplayKitRecording'}}}

# fixtures/rtl.mp4: an ordinary 24000/1001 fps YouTube download.
RTL: dict[str, Any] = {'streams': [{'index': 0,
              'codec_name': 'h264',
              'codec_type': 'video',
              'codec_tag_string': 'avc1',
              'width': 1920,
              'height': 1080,
              'pix_fmt': 'yuv420p',
              'color_range': 'tv',
              'color_space': 'bt709',
              'color_transfer': 'bt709',
              'color_primaries': 'bt709',
              'r_frame_rate': '24000/1001',
              'avg_frame_rate': '24000/1001',
              'time_base': '1/24000',
              'duration': '30.030000',
              'bit_rate': '3085857',
              'nb_frames': '720',
              'disposition': {'default': 1},
              'tags': {'language': 'und',
                       'handler_name': 'ISO Media file produced by Google Inc.',
                       'encoder': 'Lavc62.28.101 libx264'}},
             {'index': 1,
              'codec_name': 'aac',
              'codec_type': 'audio',
              'codec_tag_string': 'mp4a',
              'r_frame_rate': '0/0',
              'avg_frame_rate': '0/0',
              'time_base': '1/44100',
              'duration': '30.000000',
              'bit_rate': '128563',
              'nb_frames': '1293',
              'sample_rate': '44100',
              'channels': 2,
              'channel_layout': 'stereo',
              'disposition': {'default': 1},
              'tags': {'language': 'eng',
                       'handler_name': 'ISO Media file produced by Google Inc.'}}],
 'format': {'filename': 'fixtures/rtl.mp4',
            'nb_streams': 2,
            'format_name': 'mov,mp4,m4a,3gp,3g2,mj2',
            'format_long_name': 'QuickTime / MOV',
            'duration': '30.030000',
            'size': '12090426',
            'bit_rate': '3220892',
            'tags': {'major_brand': 'isom', 'encoder': 'Lavf62.12.101'}}}

# Synthetic HDR (PQ) clip. With ffmpeg 8.1.1 the -color_* output flags alone
# left color_transfer "unknown" in the MP4; the setparams filter tags it:
#   ffmpeg -f lavfi -i testsrc2=size=320x180:rate=30 -t 1 \
#     -vf setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc \
#     -c:v libx264 -pix_fmt yuv420p10le -color_primaries bt2020 \
#     -color_trc smpte2084 -colorspace bt2020nc hdr.mp4
HDR: dict[str, Any] = {'streams': [{'index': 0,
              'codec_name': 'h264',
              'codec_type': 'video',
              'codec_tag_string': 'avc1',
              'width': 320,
              'height': 180,
              'pix_fmt': 'yuv420p10le',
              'color_range': 'tv',
              'color_space': 'bt2020nc',
              'color_transfer': 'smpte2084',
              'color_primaries': 'bt2020',
              'r_frame_rate': '30/1',
              'avg_frame_rate': '30/1',
              'time_base': '1/15360',
              'duration': '1.000000',
              'bit_rate': '249728',
              'nb_frames': '30',
              'disposition': {'default': 1},
              'tags': {'language': 'und',
                       'handler_name': 'VideoHandler',
                       'encoder': 'Lavc62.28.101 libx264'}}],
 'format': {'filename': 'hdr.mp4',
            'nb_streams': 1,
            'format_name': 'mov,mp4,m4a,3gp,3g2,mj2',
            'format_long_name': 'QuickTime / MOV',
            'duration': '1.000000',
            'size': '32467',
            'bit_rate': '259736',
            'tags': {'major_brand': 'isom', 'encoder': 'Lavf62.12.101'}}}

# Synthetic OBS-style Matroska with three audio tracks. The trap: the DEFAULT
# flag is on the mono "System audio" track (a:1) while the stereo "Mic" (a:0)
# has the most channels; a:2 has a title but no language tag.
#   ffmpeg -f lavfi -i testsrc2=size=320x180:rate=30 \
#     -f lavfi -i sine=frequency=440:sample_rate=48000 \
#     -f lavfi -i sine=frequency=880:sample_rate=48000 \
#     -f lavfi -i sine=frequency=220:sample_rate=48000 -t 1 \
#     -map 0:v:0 -map 1:a:0 -map 2:a:0 -map 3:a:0 -c:v libx264 -pix_fmt yuv420p \
#     -c:a aac -ac:a:0 2 -ac:a:1 1 -ac:a:2 1 \
#     -metadata:s:a:0 language=eng -metadata:s:a:0 title=Mic \
#     -metadata:s:a:1 language=eng -metadata:s:a:1 title="System audio" \
#     -metadata:s:a:2 title=Music -disposition:a:1 default multitrack.mkv
MULTITRACK: dict[str, Any] = {'streams': [{'index': 0,
              'codec_name': 'h264',
              'codec_type': 'video',
              'codec_tag_string': '[0][0][0][0]',
              'width': 320,
              'height': 180,
              'pix_fmt': 'yuv420p',
              'color_range': 'tv',
              'r_frame_rate': '30/1',
              'avg_frame_rate': '30/1',
              'time_base': '1/1000',
              'disposition': {'default': 0},
              'tags': {'ENCODER': 'Lavc62.28.101 libx264',
                       'DURATION': '00:00:01.000000000'}},
             {'index': 1,
              'codec_name': 'aac',
              'codec_type': 'audio',
              'codec_tag_string': '[0][0][0][0]',
              'r_frame_rate': '0/0',
              'avg_frame_rate': '0/0',
              'time_base': '1/1000',
              'sample_rate': '48000',
              'channels': 2,
              'channel_layout': 'stereo',
              'disposition': {'default': 0},
              'tags': {'language': 'eng',
                       'title': 'Mic',
                       'ENCODER': 'Lavc62.28.101 aac',
                       'DURATION': '00:00:01.021000000'}},
             {'index': 2,
              'codec_name': 'aac',
              'codec_type': 'audio',
              'codec_tag_string': '[0][0][0][0]',
              'r_frame_rate': '0/0',
              'avg_frame_rate': '0/0',
              'time_base': '1/1000',
              'sample_rate': '48000',
              'channels': 1,
              'channel_layout': 'mono',
              'disposition': {'default': 1},
              'tags': {'language': 'eng',
                       'title': 'System audio',
                       'ENCODER': 'Lavc62.28.101 aac',
                       'DURATION': '00:00:01.021000000'}},
             {'index': 3,
              'codec_name': 'aac',
              'codec_type': 'audio',
              'codec_tag_string': '[0][0][0][0]',
              'r_frame_rate': '0/0',
              'avg_frame_rate': '0/0',
              'time_base': '1/1000',
              'sample_rate': '48000',
              'channels': 1,
              'channel_layout': 'mono',
              'disposition': {'default': 0},
              'tags': {'title': 'Music',
                       'ENCODER': 'Lavc62.28.101 aac',
                       'DURATION': '00:00:01.021000000'}}],
 'format': {'filename': 'multitrack.mkv',
            'nb_streams': 4,
            'format_name': 'matroska,webm',
            'format_long_name': 'Matroska / WebM',
            'duration': '1.021000',
            'size': '68201',
            'bit_rate': '534385',
            'tags': {'ENCODER': 'Lavf62.12.101'}}}
